import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
const inter=Inter({subsets:["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} `}
      >
        <Header/>
        
        <main className="min-h-screen">
        {children}
        </main>
        <Toaster richColors/>
        
        <footer className="bg-blue-50 py-12">
          <div className="container mx-auto  text-center text-gray-500">
            <p>
              Made By mem
            </p>
          </div>
          </footer>

      </body>
    </html>
    </ClerkProvider>
  );
}
